local D = {}

-- Read by gcauto.mb_packet: proc kind -> property, pet messages, and the action ids per category.

D.PROPNUM = {
    [1] = 'Light',
    [2] = 'Darkness',
    [3] = 'Gravitation',
    [4] = 'Fragmentation',
    [5] = 'Distortion',
    [6] = 'Fusion',
    [7] = 'Compression',
    [8] = 'Liquefaction',
    [9] = 'Induration',
    [10] = 'Reverberation',
    [11] = 'Transfixion',
    [12] = 'Scission',
    [13] = 'Detonation',
    [14] = 'Impaction',
    [15] = 'Radiance',
    [16] = 'Umbra',
}

D.PETMSG  = { [110]=true, [317]=true }

D.SPID = {
    [144] = { p={'Liquefaction'} },
    [145] = { p={'Liquefaction'} },
    [146] = { p={'Liquefaction'} },
    [147] = { p={'Liquefaction'} },
    [148] = { p={'Liquefaction'} },
    [149] = { p={'Induration'} },
    [150] = { p={'Induration'} },
    [151] = { p={'Induration'} },
    [152] = { p={'Induration'} },
    [153] = { p={'Induration'} },
    [154] = { p={'Detonation'} },
    [155] = { p={'Detonation'} },
    [156] = { p={'Detonation'} },
    [157] = { p={'Detonation'} },
    [158] = { p={'Detonation'} },
    [159] = { p={'Scission'} },
    [160] = { p={'Scission'} },
    [161] = { p={'Scission'} },
    [162] = { p={'Scission'} },
    [163] = { p={'Scission'} },
    [164] = { p={'Impaction'} },
    [165] = { p={'Impaction'} },
    [166] = { p={'Impaction'} },
    [167] = { p={'Impaction'} },
    [168] = { p={'Impaction'} },
    [169] = { p={'Reverberation'} },
    [170] = { p={'Reverberation'} },
    [171] = { p={'Reverberation'} },
    [172] = { p={'Reverberation'} },
    [173] = { p={'Reverberation'} },
    [278] = { p={'Scission'}, d=5 },
    [279] = { p={'Reverberation'}, d=5 },
    [280] = { p={'Detonation'}, d=5 },
    [281] = { p={'Liquefaction'}, d=5 },
    [282] = { p={'Induration'}, d=5 },
    [283] = { p={'Impaction'}, d=5 },
    [284] = { p={'Compression'}, d=5 },
    [285] = { p={'Transfixion'}, d=5 },
    [503] = { p={'Compression'} },
    [519] = { p={'Transfixion','Scission'} },
    [527] = { p={'Detonation'} },
    [529] = { p={'Liquefaction'} },
    [539] = { p={'Compression','Reverberation'} },
    [540] = { p={'Scission','Detonation'} },
    [543] = { p={'Induration'} },
    [545] = { p={'Compression'} },
    [551] = { p={'Reverberation'} },
    [554] = { p={'Compression','Reverberation'} },
    [560] = { p={'Induration'} },
    [564] = { p={'Impaction'} },
    [567] = { p={'Transfixion'} },
    [569] = { p={'Impaction'} },
    [577] = { p={'Detonation'} },
    [585] = { p={'Fragmentation'} },
    [587] = { p={'Scission'} },
    [589] = { p={'Transfixion','Impaction'} },
    [594] = { p={'Liquefaction','Impaction'} },
    [596] = { p={'Liquefaction'} },
    [597] = { p={'Reverberation'} },
    [599] = { p={'Compression'} },
    [603] = { p={'Transfixion'} },
    [611] = { p={'Distortion'} },
    [617] = { p={'Gravitation'} },
    [620] = { p={'Impaction'} },
    [622] = { p={'Induration'} },
    [623] = { p={'Impaction'} },
    [628] = { p={'Impaction'} },
    [631] = { p={'Reverberation'} },
    [638] = { p={'Transfixion'} },
    [640] = { p={'Reverberation'} },
    [641] = { p={'Detonation'} },
    [643] = { p={'Fusion'} },
    [650] = { p={'Induration','Detonation'} },
    [652] = { p={'Transfixion'} },
    [653] = { p={'Liquefaction','Impaction'} },
    [654] = { p={'Fragmentation'} },
    [665] = { p={'Fusion'} },
    [666] = { p={'Fusion','Impaction'} },
    [667] = { p={'Transfixion','Scission'} },
    [669] = { p={'Scission','Detonation'} },
    [670] = { p={'Gravitation','Transfixion'} },
    [673] = { p={'Distortion','Scission'} },
    [677] = { p={'Compression','Scission'} },
    [682] = { p={'Liquefaction','Detonation'} },
    [688] = { p={'Fragmentation','Transfixion'} },
    [692] = { p={'Detonation'} },
    [693] = { p={'Liquefaction','Scission','Impaction'} },
    [697] = { p={'Gravitation'} },
    [699] = { p={'Distortion','Scission'} },
    [704] = { p={'Gravitation'} },
    [706] = { p={'Fragmentation'} },
    [709] = { p={'Fusion'} },
    [714] = { p={'Gravitation','Reverberation'} },
    [723] = { p={'Fragmentation','Distortion'} },
    [740] = { p={'Light','Fragmentation'} },
    [742] = { p={'Darkness','Gravitation'} },
    [743] = { p={'Darkness','Distortion'} },
    [885] = { p={'Scission'}, d=5 },
    [886] = { p={'Reverberation'}, d=5 },
    [887] = { p={'Detonation'}, d=5 },
    [888] = { p={'Liquefaction'}, d=5 },
    [889] = { p={'Induration'}, d=5 },
    [890] = { p={'Impaction'}, d=5 },
    [891] = { p={'Compression'}, d=5 },
    [892] = { p={'Transfixion'}, d=5 },
}
D.PETID = {
    [513] = { p={'Transfixion'} },
    [521] = { p={'Scission'} },
    [528] = { p={'Compression'} },
    [529] = { p={'Transfixion'} },
    [534] = { p={'Gravitation','Scission'} },
    [544] = { p={'Liquefaction'} },
    [546] = { p={'Impaction'} },
    [547] = { p={'Compression'} },
    [550] = { p={'Fusion','Reverberation'} },
    [560] = { p={'Scission'} },
    [562] = { p={'Reverberation'} },
    [563] = { p={'Induration'} },
    [566] = { p={'Gravitation','Induration'} },
    [570] = { p={'Gravitation','Scission'} },
    [576] = { p={'Reverberation'} },
    [578] = { p={'Detonation'} },
    [582] = { p={'Distortion','Detonation'} },
    [592] = { p={'Detonation'} },
    [598] = { p={'Fragmentation','Scission'} },
    [608] = { p={'Induration'} },
    [612] = { p={'Scission'} },
    [614] = { p={'Distortion','Scission'} },
    [624] = { p={'Impaction'} },
    [630] = { p={'Fragmentation','Transfixion'} },
    [634] = { p={'Fragmentation','Scission'} },
    [656] = { p={'Compression'} },
    [667] = { p={'Gravitation','Transfixion'} },
    [672] = { p={'Reverberation'} },
    [674] = { p={'Impaction'} },
    [675] = { p={'Detonation'} },
    [677] = { p={'Transfixion'} },
    [678] = { p={'Scission'} },
    [681] = { p={'Impaction'} },
    [682] = { p={'Scission'} },
    [683] = { p={'Impaction'} },
    [685] = { p={'Reverberation'} },
    [686] = { p={'Liquefaction'} },
    [689] = { p={'Impaction'} },
    [691] = { p={'Reverberation'} },
    [695] = { p={'Scission'} },
    [698] = { p={'Transfixion'} },
    [699] = { p={'Darkness','Fragmentation'} },
    [700] = { p={'Compression'} },
    [707] = { p={'Reverberation'} },
    [709] = { p={'Detonation'} },
    [717] = { p={'Detonation'} },
    [723] = { p={'Impaction'} },
    [724] = { p={'Impaction'} },
    [726] = { p={'Liquefaction'} },
    [727] = { p={'Reverberation'} },
    [728] = { p={'Impaction'} },
    [732] = { p={'Compression'} },
    [736] = { p={'Impaction'} },
    [737] = { p={'Scission'} },
    [743] = { p={'Liquefaction'} },
    [744] = { p={'Induration'} },
    [745] = { p={'Darkness','Gravitation'} },
    [749] = { p={'Reverberation'} },
    [753] = { p={'Liquefaction'} },
    [756] = { p={'Gravitation','Liquefaction'} },
    [757] = { p={'Scission'} },
    [759] = { p={'Transfixion'} },
    [761] = { p={'Scission'} },
    [762] = { p={'Distortion','Detonation'} },
    [764] = { p={'Fusion','Reverberation'} },
    [765] = { p={'Induration'} },
    [767] = { p={'Light','Distortion'} },
    [768] = { p={'Impaction'} },
    [772] = { p={'Compression'} },
    [776] = { p={'Transfixion'} },
    [777] = { p={'Transfixion'} },
    [780] = { p={'Distortion','Detonation'} },
    [961] = { p={'Scission'} },
    [964] = { p={'Detonation'} },
    [970] = { p={'Fragmentation','Transfixion'} },
}
D.CBID = {
    [209] = { p={'Compression','Liquefaction','Induration','Reverberation','Scission'} },
    [320] = { p={'Light','Darkness','Gravitation','Fragmentation','Distortion','Compression','Liquefaction','Induration','Reverberation','Scission'} },
}
-- 3 (WS) needs no table: XiPackets gives proc_kind as the chain id for weapon skills.
D.BYCAT = { [4]=D.SPID, [13]=D.PETID, [14]=D.CBID }

return D
