local D = {}

D.CHAIN = {
    Compression   = { lv = 1, Detonation={1,'Detonation'}, Transfixion={1,'Transfixion'} },
    Detonation    = { lv = 1, Compression={2,'Gravitation'}, Scission={1,'Scission'} },
    Impaction     = { lv = 1, Detonation={1,'Detonation'}, Liquefaction={1,'Liquefaction'} },
    Induration    = { lv = 1, Compression={1,'Compression'}, Impaction={1,'Impaction'}, Reverberation={2,'Fragmentation'} },
    Liquefaction  = { lv = 1, Impaction={2,'Fusion'}, Scission={1,'Scission'} },
    Reverberation = { lv = 1, Impaction={1,'Impaction'}, Induration={1,'Induration'} },
    Scission      = { lv = 1, Detonation={1,'Detonation'}, Liquefaction={1,'Liquefaction'}, Reverberation={1,'Reverberation'} },
    Transfixion   = { lv = 1, Compression={1,'Compression'}, Reverberation={1,'Reverberation'}, Scission={2,'Distortion'} },
    Distortion    = { lv = 2, Fusion={2,'Fusion'}, Gravitation={3,'Darkness'} },
    Fragmentation = { lv = 2, Distortion={2,'Distortion'}, Fusion={3,'Light'} },
    Fusion        = { lv = 2, Fragmentation={3,'Light'}, Gravitation={2,'Gravitation'} },
    Gravitation   = { lv = 2, Distortion={3,'Darkness'}, Fragmentation={2,'Fragmentation'} },
    Darkness      = { lv = 3, Darkness={4,'Darkness'} },
    Light         = { lv = 3, Light={4,'Light'} },
    Radiance      = { lv = 4 },
    Umbra         = { lv = 4 },
}

D.PROPNUM = {
    [1] = 'Light',
    [2] = 'Darkness',
    [3] = 'Gravitation',
    [4] = 'Fragmentation',
    [5] = 'Distortion',
    [6] = 'Fusion',
    [7] = 'Compression',
    [8] = 'Liquefaction',
    [9] = 'Induration',
    [10] = 'Reverberation',
    [11] = 'Transfixion',
    [12] = 'Scission',
    [13] = 'Detonation',
    [14] = 'Impaction',
    [15] = 'Radiance',
    [16] = 'Umbra',
}

D.MSG     = { [2]=true, [110]=true, [185]=true, [187]=true, [317]=true, [802]=true }
D.PETMSG  = { [110]=true, [317]=true }
D.MSG_CHAINBOUND = 529

D.SPELL = {
    ['Fire']      = { id = 144, prop = 'Liquefaction', delay = 3 },
    ['Thunder']   = { id = 164, prop = 'Impaction', delay = 3 },
    ['Stone']     = { id = 159, prop = 'Scission', delay = 3 },
    ['Water']     = { id = 169, prop = 'Reverberation', delay = 3 },
    ['Blizzard']  = { id = 149, prop = 'Induration', delay = 3 },
    ['Aero']      = { id = 154, prop = 'Detonation', delay = 3 },
    ['Noctohelix'] = { id = 284, prop = 'Compression', delay = 5 },
    ['Luminohelix'] = { id = 285, prop = 'Transfixion', delay = 5 },
}
D.SPELL_ORDER = { 'Fire', 'Thunder', 'Stone', 'Water', 'Blizzard', 'Aero', 'Noctohelix', 'Luminohelix' }

D.WSID = {
    [1] = { p={'Impaction'} },
    [2] = { p={'Reverberation','Impaction'} },
    [3] = { p={'Compression'} },
    [4] = { p={'Detonation'} },
    [5] = { p={'Impaction'} },
    [6] = { p={'Liquefaction','Impaction'} },
    [7] = { p={'Transfixion','Impaction'} },
    [8] = { p={'Fragmentation'} },
    [9] = { p={'Gravitation','Liquefaction'} },
    [10] = { p={'Light','Fusion'} },
    [11] = { p={'Fusion','Transfixion'} },
    [12] = { p={'Gravitation','Liquefaction'} },
    [13] = { p={'Induration','Detonation','Impaction'} },
    [14] = { p={'Light','Fragmentation'} },
    [15] = { p={'Fusion','Reverberation'} },
    [16] = { p={'Scission'} },
    [17] = { p={'Scission'} },
    [18] = { p={'Reverberation'} },
    [19] = { p={'Detonation'} },
    [20] = { p={'Detonation','Impaction'} },
    [23] = { p={'Scission','Detonation'} },
    [24] = { p={'Fragmentation'} },
    [25] = { p={'Gravitation','Transfixion'} },
    [26] = { p={'Darkness','Gravitation'} },
    [27] = { p={'Fusion','Compression'} },
    [28] = { p={'Fragmentation','Distortion'} },
    [29] = { p={'Distortion','Scission'} },
    [30] = { p={'Scission','Detonation','Impaction'} },
    [31] = { p={'Darkness','Distortion'} },
    [32] = { p={'Scission'} },
    [33] = { p={'Liquefaction'} },
    [34] = { p={'Liquefaction','Detonation'} },
    [35] = { p={'Impaction'} },
    [36] = { p={'Scission'} },
    [37] = { p={'Scission'} },
    [38] = { p={'Reverberation','Impaction'} },
    [40] = { p={'Scission','Impaction'} },
    [41] = { p={'Gravitation'} },
    [42] = { p={'Fragmentation','Scission'} },
    [43] = { p={'Light','Fusion'} },
    [44] = { p={'Fragmentation','Distortion'} },
    [45] = { p={'Fusion','Reverberation'} },
    [46] = { p={'Distortion','Scission'} },
    [48] = { p={'Scission'} },
    [49] = { p={'Transfixion'} },
    [50] = { p={'Induration'} },
    [51] = { p={'Induration','Detonation'} },
    [52] = { p={'Reverberation'} },
    [53] = { p={'Scission'} },
    [54] = { p={'Scission','Impaction'} },
    [55] = { p={'Fragmentation'} },
    [56] = { p={'Fragmentation','Distortion'} },
    [57] = { p={'Light','Fusion'} },
    [58] = { p={'Induration','Detonation','Impaction'} },
    [59] = { p={'Light','Distortion'} },
    [60] = { p={'Fragmentation','Scission'} },
    [61] = { p={'Light','Fragmentation'} },
    [62] = { p={'Detonation','Compression','Distortion'} },
    [64] = { p={'Detonation','Impaction'} },
    [65] = { p={'Induration','Reverberation'} },
    [66] = { p={'Detonation'} },
    [67] = { p={'Scission','Impaction'} },
    [68] = { p={'Liquefaction','Scission','Impaction'} },
    [69] = { p={'Scission'} },
    [70] = { p={'Scission','Impaction'} },
    [71] = { p={'Fusion'} },
    [72] = { p={'Fusion','Reverberation'} },
    [73] = { p={'Darkness','Gravitation'} },
    [74] = { p={'Gravitation','Reverberation'} },
    [75] = { p={'Scission','Detonation'} },
    [76] = { p={'Darkness','Fragmentation'} },
    [77] = { p={'Distortion','Detonation'} },
    [78] = { p={'Liquefaction','Impaction','Fragmentation'} },
    [80] = { p={'Impaction'} },
    [81] = { p={'Scission'} },
    [82] = { p={'Reverberation','Scission'} },
    [83] = { p={'Impaction'} },
    [84] = { p={'Compression'} },
    [85] = { p={'Impaction'} },
    [86] = { p={'Induration','Reverberation'} },
    [87] = { p={'Distortion'} },
    [88] = { p={'Distortion','Detonation'} },
    [89] = { p={'Light','Fusion'} },
    [90] = { p={'Fragmentation','Scission'} },
    [91] = { p={'Scission','Detonation','Impaction'} },
    [92] = { p={'Light','Fragmentation'} },
    [93] = { p={'Fusion','Compression'} },
    [94] = { p={'Transfixion','Scission','Gravitation'} },
    [96] = { p={'Scission'} },
    [97] = { p={'Reverberation'} },
    [98] = { p={'Induration','Reverberation'} },
    [99] = { p={'Compression','Scission'} },
    [100] = { p={'Reverberation','Scission'} },
    [101] = { p={'Transfixion','Scission'} },
    [102] = { p={'Induration'} },
    [103] = { p={'Distortion'} },
    [104] = { p={'Distortion','Scission'} },
    [105] = { p={'Darkness','Gravitation'} },
    [106] = { p={'Fusion','Compression'} },
    [107] = { p={'Compression','Reverberation'} },
    [108] = { p={'Darkness','Distortion'} },
    [109] = { p={'Gravitation','Reverberation'} },
    [110] = { p={'Induration','Reverberation','Fusion'} },
    [112] = { p={'Transfixion'} },
    [113] = { p={'Transfixion','Impaction'} },
    [114] = { p={'Transfixion','Impaction'} },
    [115] = { p={'Impaction'} },
    [116] = { p={'Compression'} },
    [117] = { p={'Reverberation','Transfixion'} },
    [118] = { p={'Transfixion','Impaction'} },
    [119] = { p={'Fusion'} },
    [120] = { p={'Gravitation','Induration'} },
    [121] = { p={'Light','Distortion'} },
    [122] = { p={'Fusion','Transfixion'} },
    [123] = { p={'Transfixion','Scission'} },
    [124] = { p={'Light','Fragmentation'} },
    [125] = { p={'Gravitation','Transfixion'} },
    [126] = { p={'Transfixion','Scission','Gravitation'} },
    [128] = { p={'Transfixion'} },
    [129] = { p={'Scission'} },
    [130] = { p={'Reverberation'} },
    [131] = { p={'Induration','Detonation'} },
    [132] = { p={'Transfixion','Impaction'} },
    [133] = { p={'Compression'} },
    [134] = { p={'Detonation','Impaction'} },
    [135] = { p={'Gravitation'} },
    [136] = { p={'Gravitation','Transfixion'} },
    [137] = { p={'Darkness','Fragmentation'} },
    [138] = { p={'Fragmentation','Compression'} },
    [139] = { p={'Reverberation','Scission'} },
    [140] = { p={'Darkness','Gravitation'} },
    [141] = { p={'Fusion','Impaction'} },
    [142] = { p={'Induration','Reverberation','Fusion'} },
    [144] = { p={'Transfixion','Scission'} },
    [145] = { p={'Induration'} },
    [146] = { p={'Transfixion','Impaction'} },
    [147] = { p={'Liquefaction'} },
    [148] = { p={'Scission','Detonation'} },
    [149] = { p={'Reverberation','Impaction'} },
    [150] = { p={'Induration','Detonation'} },
    [151] = { p={'Distortion','Reverberation'} },
    [152] = { p={'Fusion','Compression'} },
    [153] = { p={'Light','Fragmentation'} },
    [154] = { p={'Gravitation','Induration'} },
    [155] = { p={'Compression','Scission'} },
    [156] = { p={'Light','Distortion'} },
    [157] = { p={'Fragmentation','Compression'} },
    [158] = { p={'Fusion'} },
    [159] = { p={'Detonation','Compression','Distortion'} },
    [160] = { p={'Impaction'} },
    [161] = { p={'Impaction'} },
    [162] = { p={'Reverberation'} },
    [165] = { p={'Induration','Reverberation'} },
    [166] = { p={'Detonation','Impaction'} },
    [167] = { p={'Impaction'} },
    [168] = { p={'Fusion'} },
    [169] = { p={'Fragmentation','Compression'} },
    [170] = { p={'Light','Fragmentation'} },
    [172] = { p={'Induration','Reverberation'} },
    [174] = { p={'Fusion','Impaction'} },
    [175] = { p={'Darkness','Fragmentation'} },
    [176] = { p={'Impaction'} },
    [177] = { p={'Impaction'} },
    [178] = { p={'Detonation','Impaction'} },
    [179] = { p={'Compression','Reverberation'} },
    [180] = { p={'Compression','Reverberation'} },
    [181] = { p={'Detonation'} },
    [182] = { p={'Liquefaction','Impaction'} },
    [184] = { p={'Gravitation','Reverberation'} },
    [185] = { p={'Darkness','Distortion'} },
    [186] = { p={'Fragmentation','Distortion'} },
    [187] = { p={'Fusion','Reverberation'} },
    [188] = { p={'Gravitation','Transfixion'} },
    [189] = { p={'Compression','Reverberation'} },
    [191] = { p={'Gravitation','Induration'} },
    [192] = { p={'Liquefaction','Transfixion'} },
    [193] = { p={'Reverberation','Transfixion'} },
    [194] = { p={'Liquefaction','Transfixion'} },
    [196] = { p={'Reverberation','Transfixion','Detonation'} },
    [197] = { p={'Induration','Transfixion'} },
    [198] = { p={'Fusion'} },
    [199] = { p={'Fusion','Transfixion'} },
    [200] = { p={'Light','Distortion'} },
    [201] = { p={'Reverberation','Transfixion'} },
    [202] = { p={'Light','Fusion'} },
    [203] = { p={'Fragmentation','Transfixion'} },
    [204] = { p={'Transfixion','Scission','Gravitation'} },
    [208] = { p={'Liquefaction','Transfixion'} },
    [209] = { p={'Reverberation','Transfixion'} },
    [210] = { p={'Liquefaction','Transfixion'} },
    [212] = { p={'Reverberation','Transfixion','Detonation'} },
    [213] = { p={'Induration','Transfixion'} },
    [214] = { p={'Fusion'} },
    [215] = { p={'Fusion','Transfixion'} },
    [216] = { p={'Darkness','Fragmentation'} },
    [217] = { p={'Fragmentation','Scission'} },
    [218] = { p={'Gravitation','Transfixion'} },
    [219] = { p={'Induration','Detonation','Impaction'} },
    [220] = { p={'Darkness','Gravitation'} },
    [221] = { p={'Fusion','Reverberation'} },
    [222] = { p={'Induration','Reverberation','Fusion'} },
    [224] = { p={'Fragmentation','Scission'} },
    [225] = { p={'Light','Distortion'} },
    [226] = { p={'Gravitation','Scission'} },
    [227] = { p={'Light'} },
    [228] = { p={'Light'} },
    [229] = { p={'Fusion'} },
    [230] = { p={'Distortion'} },
    [231] = { p={'Detonation','Compression','Distortion'} },
    [232] = { p={'Liquefaction','Impaction','Fragmentation'} },
    [233] = { p={'Detonation','Compression','Distortion'} },
    [234] = { p={'Transfixion','Scission','Gravitation'} },
    [235] = { p={'Induration','Reverberation','Fusion'} },
    [238] = { p={'Light','Fragmentation'} },
    [239] = { p={'Light','Fusion'} },
}
D.SPID = {
    [144] = { p={'Liquefaction'} },
    [145] = { p={'Liquefaction'} },
    [146] = { p={'Liquefaction'} },
    [147] = { p={'Liquefaction'} },
    [148] = { p={'Liquefaction'} },
    [149] = { p={'Induration'} },
    [150] = { p={'Induration'} },
    [151] = { p={'Induration'} },
    [152] = { p={'Induration'} },
    [153] = { p={'Induration'} },
    [154] = { p={'Detonation'} },
    [155] = { p={'Detonation'} },
    [156] = { p={'Detonation'} },
    [157] = { p={'Detonation'} },
    [158] = { p={'Detonation'} },
    [159] = { p={'Scission'} },
    [160] = { p={'Scission'} },
    [161] = { p={'Scission'} },
    [162] = { p={'Scission'} },
    [163] = { p={'Scission'} },
    [164] = { p={'Impaction'} },
    [165] = { p={'Impaction'} },
    [166] = { p={'Impaction'} },
    [167] = { p={'Impaction'} },
    [168] = { p={'Impaction'} },
    [169] = { p={'Reverberation'} },
    [170] = { p={'Reverberation'} },
    [171] = { p={'Reverberation'} },
    [172] = { p={'Reverberation'} },
    [173] = { p={'Reverberation'} },
    [278] = { p={'Scission'}, d=5 },
    [279] = { p={'Reverberation'}, d=5 },
    [280] = { p={'Detonation'}, d=5 },
    [281] = { p={'Liquefaction'}, d=5 },
    [282] = { p={'Induration'}, d=5 },
    [283] = { p={'Impaction'}, d=5 },
    [284] = { p={'Compression'}, d=5 },
    [285] = { p={'Transfixion'}, d=5 },
    [503] = { p={'Compression'} },
    [519] = { p={'Transfixion','Scission'} },
    [527] = { p={'Detonation'} },
    [529] = { p={'Liquefaction'} },
    [539] = { p={'Compression','Reverberation'} },
    [540] = { p={'Scission','Detonation'} },
    [543] = { p={'Induration'} },
    [545] = { p={'Compression'} },
    [551] = { p={'Reverberation'} },
    [554] = { p={'Compression','Reverberation'} },
    [560] = { p={'Induration'} },
    [564] = { p={'Impaction'} },
    [567] = { p={'Transfixion'} },
    [569] = { p={'Impaction'} },
    [577] = { p={'Detonation'} },
    [585] = { p={'Fragmentation'} },
    [587] = { p={'Scission'} },
    [589] = { p={'Transfixion','Impaction'} },
    [594] = { p={'Liquefaction','Impaction'} },
    [596] = { p={'Liquefaction'} },
    [597] = { p={'Reverberation'} },
    [599] = { p={'Compression'} },
    [603] = { p={'Transfixion'} },
    [611] = { p={'Distortion'} },
    [617] = { p={'Gravitation'} },
    [620] = { p={'Impaction'} },
    [622] = { p={'Induration'} },
    [623] = { p={'Impaction'} },
    [628] = { p={'Impaction'} },
    [631] = { p={'Reverberation'} },
    [638] = { p={'Transfixion'} },
    [640] = { p={'Reverberation'} },
    [641] = { p={'Detonation'} },
    [643] = { p={'Fusion'} },
    [650] = { p={'Induration','Detonation'} },
    [652] = { p={'Transfixion'} },
    [653] = { p={'Liquefaction','Impaction'} },
    [654] = { p={'Fragmentation'} },
    [665] = { p={'Fusion'} },
    [666] = { p={'Fusion','Impaction'} },
    [667] = { p={'Transfixion','Scission'} },
    [669] = { p={'Scission','Detonation'} },
    [670] = { p={'Gravitation','Transfixion'} },
    [673] = { p={'Distortion','Scission'} },
    [677] = { p={'Compression','Scission'} },
    [682] = { p={'Liquefaction','Detonation'} },
    [688] = { p={'Fragmentation','Transfixion'} },
    [692] = { p={'Detonation'} },
    [693] = { p={'Liquefaction','Scission','Impaction'} },
    [697] = { p={'Gravitation'} },
    [699] = { p={'Distortion','Scission'} },
    [704] = { p={'Gravitation'} },
    [706] = { p={'Fragmentation'} },
    [709] = { p={'Fusion'} },
    [714] = { p={'Gravitation','Reverberation'} },
    [723] = { p={'Fragmentation','Distortion'} },
    [740] = { p={'Light','Fragmentation'} },
    [742] = { p={'Darkness','Gravitation'} },
    [743] = { p={'Darkness','Distortion'} },
    [885] = { p={'Scission'}, d=5 },
    [886] = { p={'Reverberation'}, d=5 },
    [887] = { p={'Detonation'}, d=5 },
    [888] = { p={'Liquefaction'}, d=5 },
    [889] = { p={'Induration'}, d=5 },
    [890] = { p={'Impaction'}, d=5 },
    [891] = { p={'Compression'}, d=5 },
    [892] = { p={'Transfixion'}, d=5 },
}
D.PETID = {
    [513] = { p={'Transfixion'} },
    [521] = { p={'Scission'} },
    [528] = { p={'Compression'} },
    [529] = { p={'Transfixion'} },
    [534] = { p={'Gravitation','Scission'} },
    [544] = { p={'Liquefaction'} },
    [546] = { p={'Impaction'} },
    [547] = { p={'Compression'} },
    [550] = { p={'Fusion','Reverberation'} },
    [560] = { p={'Scission'} },
    [562] = { p={'Reverberation'} },
    [563] = { p={'Induration'} },
    [566] = { p={'Gravitation','Induration'} },
    [570] = { p={'Gravitation','Scission'} },
    [576] = { p={'Reverberation'} },
    [578] = { p={'Detonation'} },
    [582] = { p={'Distortion','Detonation'} },
    [592] = { p={'Detonation'} },
    [598] = { p={'Fragmentation','Scission'} },
    [608] = { p={'Induration'} },
    [612] = { p={'Scission'} },
    [614] = { p={'Distortion','Scission'} },
    [624] = { p={'Impaction'} },
    [630] = { p={'Fragmentation','Transfixion'} },
    [634] = { p={'Fragmentation','Scission'} },
    [656] = { p={'Compression'} },
    [667] = { p={'Gravitation','Transfixion'} },
    [672] = { p={'Reverberation'} },
    [674] = { p={'Impaction'} },
    [675] = { p={'Detonation'} },
    [677] = { p={'Transfixion'} },
    [678] = { p={'Scission'} },
    [681] = { p={'Impaction'} },
    [682] = { p={'Scission'} },
    [683] = { p={'Impaction'} },
    [685] = { p={'Reverberation'} },
    [686] = { p={'Liquefaction'} },
    [689] = { p={'Impaction'} },
    [691] = { p={'Reverberation'} },
    [695] = { p={'Scission'} },
    [698] = { p={'Transfixion'} },
    [699] = { p={'Darkness','Fragmentation'} },
    [700] = { p={'Compression'} },
    [707] = { p={'Reverberation'} },
    [709] = { p={'Detonation'} },
    [717] = { p={'Detonation'} },
    [723] = { p={'Impaction'} },
    [724] = { p={'Impaction'} },
    [726] = { p={'Liquefaction'} },
    [727] = { p={'Reverberation'} },
    [728] = { p={'Impaction'} },
    [732] = { p={'Compression'} },
    [736] = { p={'Impaction'} },
    [737] = { p={'Scission'} },
    [743] = { p={'Liquefaction'} },
    [744] = { p={'Induration'} },
    [745] = { p={'Darkness','Gravitation'} },
    [749] = { p={'Reverberation'} },
    [753] = { p={'Liquefaction'} },
    [756] = { p={'Gravitation','Liquefaction'} },
    [757] = { p={'Scission'} },
    [759] = { p={'Transfixion'} },
    [761] = { p={'Scission'} },
    [762] = { p={'Distortion','Detonation'} },
    [764] = { p={'Fusion','Reverberation'} },
    [765] = { p={'Induration'} },
    [767] = { p={'Light','Distortion'} },
    [768] = { p={'Impaction'} },
    [772] = { p={'Compression'} },
    [776] = { p={'Transfixion'} },
    [777] = { p={'Transfixion'} },
    [780] = { p={'Distortion','Detonation'} },
    [961] = { p={'Scission'} },
    [964] = { p={'Detonation'} },
    [970] = { p={'Fragmentation','Transfixion'} },
}
D.CBID = {
    [209] = { p={'Compression','Liquefaction','Induration','Reverberation','Scission'} },
    [320] = { p={'Light','Darkness','Gravitation','Fragmentation','Distortion','Compression','Liquefaction','Induration','Reverberation','Scission'} },
}
D.BYCAT = { [3]=D.WSID, [4]=D.SPID, [11]=nil, [13]=D.PETID, [14]=D.CBID }

-- D.WSNAME: reference only, not read by the engine (gcauto uses the id tables via D.BYCAT).
D.WSNAME = {
    ['Combo'] = {'Impaction'},
    ['Shoulder Tackle'] = {'Reverberation','Impaction'},
    ['One Inch Punch'] = {'Compression'},
    ['Backhand Blow'] = {'Detonation'},
    ['Raging Fists'] = {'Impaction'},
    ['Spinning Attack'] = {'Liquefaction','Impaction'},
    ['Howling Fist'] = {'Transfixion','Impaction'},
    ['Dragon Kick'] = {'Fragmentation'},
    ['Asuran Fists'] = {'Gravitation','Liquefaction'},
    ['Final Heaven'] = {'Light','Fusion'},
    ['Ascetic\'s Fury'] = {'Fusion','Transfixion'},
    ['Stringing Pummel'] = {'Gravitation','Liquefaction'},
    ['Tornado Kick'] = {'Induration','Detonation','Impaction'},
    ['Victory Smite'] = {'Light','Fragmentation'},
    ['Shijin Spiral'] = {'Fusion','Reverberation'},
    ['Wasp Sting'] = {'Scission'},
    ['Viper Bite'] = {'Scission'},
    ['Shadowstitch'] = {'Reverberation'},
    ['Gust Slash'] = {'Detonation'},
    ['Cyclone'] = {'Detonation','Impaction'},
    ['Dancing Edge'] = {'Scission','Detonation'},
    ['Shark Bite'] = {'Fragmentation'},
    ['Evisceration'] = {'Gravitation','Transfixion'},
    ['Mercy Stroke'] = {'Darkness','Gravitation'},
    ['Mandalic Stab'] = {'Fusion','Compression'},
    ['Mordant Rime'] = {'Fragmentation','Distortion'},
    ['Pyrrhic Kleos'] = {'Distortion','Scission'},
    ['Aeolian Edge'] = {'Scission','Detonation','Impaction'},
    ['Rudra\'s Storm'] = {'Darkness','Distortion'},
    ['Fast Blade'] = {'Scission'},
    ['Burning Blade'] = {'Liquefaction'},
    ['Red Lotus Blade'] = {'Liquefaction','Detonation'},
    ['Flat Blade'] = {'Impaction'},
    ['Shining Blade'] = {'Scission'},
    ['Seraph Blade'] = {'Scission'},
    ['Circle Blade'] = {'Reverberation','Impaction'},
    ['Vorpal Blade'] = {'Scission','Impaction'},
    ['Swift Blade'] = {'Gravitation'},
    ['Savage Blade'] = {'Fragmentation','Scission'},
    ['Knights of Round'] = {'Light','Fusion'},
    ['Death Blossom'] = {'Fragmentation','Distortion'},
    ['Atonement'] = {'Fusion','Reverberation'},
    ['Expiacion'] = {'Distortion','Scission'},
    ['Hard Slash'] = {'Scission'},
    ['Power Slash'] = {'Transfixion'},
    ['Frostbite'] = {'Induration'},
    ['Freezebite'] = {'Induration','Detonation'},
    ['Shockwave'] = {'Reverberation'},
    ['Crescent Moon'] = {'Scission'},
    ['Sickle Moon'] = {'Scission','Impaction'},
    ['Spinning Slash'] = {'Fragmentation'},
    ['Ground Strike'] = {'Fragmentation','Distortion'},
    ['Scourge'] = {'Light','Fusion'},
    ['Herculean Slash'] = {'Induration','Detonation','Impaction'},
    ['Torcleaver'] = {'Light','Distortion'},
    ['Resolution'] = {'Fragmentation','Scission'},
    ['Dimidiation'] = {'Light','Fragmentation'},
    ['Fimbulvetr'] = {'Detonation','Compression','Distortion'},
    ['Raging Axe'] = {'Detonation','Impaction'},
    ['Smash Axe'] = {'Induration','Reverberation'},
    ['Gale Axe'] = {'Detonation'},
    ['Avalanche Axe'] = {'Scission','Impaction'},
    ['Spinning Axe'] = {'Liquefaction','Scission','Impaction'},
    ['Rampage'] = {'Scission'},
    ['Calamity'] = {'Scission','Impaction'},
    ['Mistral Axe'] = {'Fusion'},
    ['Decimation'] = {'Fusion','Reverberation'},
    ['Onslaught'] = {'Darkness','Gravitation'},
    ['Primal Rend'] = {'Gravitation','Reverberation'},
    ['Bora Axe'] = {'Scission','Detonation'},
    ['Cloudsplitter'] = {'Darkness','Fragmentation'},
    ['Ruinator'] = {'Distortion','Detonation'},
    ['Blitz'] = {'Liquefaction','Impaction','Fragmentation'},
    ['Shield Break'] = {'Impaction'},
    ['Iron Tempest'] = {'Scission'},
    ['Sturmwind'] = {'Reverberation','Scission'},
    ['Armor Break'] = {'Impaction'},
    ['Keen Edge'] = {'Compression'},
    ['Weapon Break'] = {'Impaction'},
    ['Raging Rush'] = {'Induration','Reverberation'},
    ['Full Break'] = {'Distortion'},
    ['Steel Cyclone'] = {'Distortion','Detonation'},
    ['Metatron Torment'] = {'Light','Fusion'},
    ['King\'s Justice'] = {'Fragmentation','Scission'},
    ['Fell Cleave'] = {'Scission','Detonation','Impaction'},
    ['Ukko\'s Fury'] = {'Light','Fragmentation'},
    ['Upheaval'] = {'Fusion','Compression'},
    ['Disaster'] = {'Transfixion','Scission','Gravitation'},
    ['Slice'] = {'Scission'},
    ['Dark Harvest'] = {'Reverberation'},
    ['Shadow of Death'] = {'Induration','Reverberation'},
    ['Nightmare Scythe'] = {'Compression','Scission'},
    ['Spinning Scythe'] = {'Reverberation','Scission'},
    ['Vorpal Scythe'] = {'Transfixion','Scission'},
    ['Guillotine'] = {'Induration'},
    ['Cross Reaper'] = {'Distortion'},
    ['Spiral Hell'] = {'Distortion','Scission'},
    ['Catastrophe'] = {'Darkness','Gravitation'},
    ['Insurgency'] = {'Fusion','Compression'},
    ['Infernal Scythe'] = {'Compression','Reverberation'},
    ['Quietus'] = {'Darkness','Distortion'},
    ['Entropy'] = {'Gravitation','Reverberation'},
    ['Origin'] = {'Induration','Reverberation','Fusion'},
    ['Double Thrust'] = {'Transfixion'},
    ['Thunder Thrust'] = {'Transfixion','Impaction'},
    ['Raiden Thrust'] = {'Transfixion','Impaction'},
    ['Leg Sweep'] = {'Impaction'},
    ['Penta Thrust'] = {'Compression'},
    ['Vorpal Thrust'] = {'Reverberation','Transfixion'},
    ['Skewer'] = {'Transfixion','Impaction'},
    ['Wheeling Thrust'] = {'Fusion'},
    ['Impulse Drive'] = {'Gravitation','Induration'},
    ['Geirskogul'] = {'Light','Distortion'},
    ['Drakesbane'] = {'Fusion','Transfixion'},
    ['Sonic Thrust'] = {'Transfixion','Scission'},
    ['Camlann\'s Torment'] = {'Light','Fragmentation'},
    ['Stardiver'] = {'Gravitation','Transfixion'},
    ['Diarmuid'] = {'Transfixion','Scission','Gravitation'},
    ['Blade: Rin'] = {'Transfixion'},
    ['Blade: Retsu'] = {'Scission'},
    ['Blade: Teki'] = {'Reverberation'},
    ['Blade: To'] = {'Induration','Detonation'},
    ['Blade: Chi'] = {'Transfixion','Impaction'},
    ['Blade: Ei'] = {'Compression'},
    ['Blade: Jin'] = {'Detonation','Impaction'},
    ['Blade: Ten'] = {'Gravitation'},
    ['Blade: Ku'] = {'Gravitation','Transfixion'},
    ['Blade: Metsu'] = {'Darkness','Fragmentation'},
    ['Blade: Kamu'] = {'Fragmentation','Compression'},
    ['Blade: Yu'] = {'Reverberation','Scission'},
    ['Blade: Hi'] = {'Darkness','Gravitation'},
    ['Blade: Shun'] = {'Fusion','Impaction'},
    ['Zesho Meppo'] = {'Induration','Reverberation','Fusion'},
    ['Tachi: Enpi'] = {'Transfixion','Scission'},
    ['Tachi: Hobaku'] = {'Induration'},
    ['Tachi: Goten'] = {'Transfixion','Impaction'},
    ['Tachi: Kagero'] = {'Liquefaction'},
    ['Tachi: Jinpu'] = {'Scission','Detonation'},
    ['Tachi: Koki'] = {'Reverberation','Impaction'},
    ['Tachi: Yukikaze'] = {'Induration','Detonation'},
    ['Tachi: Gekko'] = {'Distortion','Reverberation'},
    ['Tachi: Kasha'] = {'Fusion','Compression'},
    ['Tachi: Kaiten'] = {'Light','Fragmentation'},
    ['Tachi: Rana'] = {'Gravitation','Induration'},
    ['Tachi: Ageha'] = {'Compression','Scission'},
    ['Tachi: Fudo'] = {'Light','Distortion'},
    ['Tachi: Shoha'] = {'Fragmentation','Compression'},
    ['Tachi: Suikawari'] = {'Fusion'},
    ['Tachi: Mumei'] = {'Detonation','Compression','Distortion'},
    ['Shining Strike'] = {'Impaction'},
    ['Seraph Strike'] = {'Impaction'},
    ['Brainshaker'] = {'Reverberation'},
    ['Skullbreaker'] = {'Induration','Reverberation'},
    ['True Strike'] = {'Detonation','Impaction'},
    ['Judgment'] = {'Impaction'},
    ['Hexa Strike'] = {'Fusion'},
    ['Black Halo'] = {'Fragmentation','Compression'},
    ['Randgrith'] = {'Light','Fragmentation'},
    ['Flash Nova'] = {'Induration','Reverberation'},
    ['Realmrazer'] = {'Fusion','Impaction'},
    ['Exudation'] = {'Darkness','Fragmentation'},
    ['Heavy Swing'] = {'Impaction'},
    ['Rock Crusher'] = {'Impaction'},
    ['Earth Crusher'] = {'Detonation','Impaction'},
    ['Starburst'] = {'Compression','Reverberation'},
    ['Sunburst'] = {'Compression','Reverberation'},
    ['Shell Crusher'] = {'Detonation'},
    ['Full Swing'] = {'Liquefaction','Impaction'},
    ['Retribution'] = {'Gravitation','Reverberation'},
    ['Gate of Tartarus'] = {'Darkness','Distortion'},
    ['Vidohunir'] = {'Fragmentation','Distortion'},
    ['Garland of Bliss'] = {'Fusion','Reverberation'},
    ['Omniscience'] = {'Gravitation','Transfixion'},
    ['Cataclysm'] = {'Compression','Reverberation'},
    ['Shattersoul'] = {'Gravitation','Induration'},
    ['Flaming Arrow'] = {'Liquefaction','Transfixion'},
    ['Piercing Arrow'] = {'Reverberation','Transfixion'},
    ['Dulling Arrow'] = {'Liquefaction','Transfixion'},
    ['Sidewinder'] = {'Reverberation','Transfixion','Detonation'},
    ['Blast Arrow'] = {'Induration','Transfixion'},
    ['Arching Arrow'] = {'Fusion'},
    ['Empyreal Arrow'] = {'Fusion','Transfixion'},
    ['Namas Arrow'] = {'Light','Distortion'},
    ['Refulgent Arrow'] = {'Reverberation','Transfixion'},
    ['Jishnu\'s Radiance'] = {'Light','Fusion'},
    ['Apex Arrow'] = {'Fragmentation','Transfixion'},
    ['Sarv'] = {'Transfixion','Scission','Gravitation'},
    ['Hot Shot'] = {'Liquefaction','Transfixion'},
    ['Split Shot'] = {'Reverberation','Transfixion'},
    ['Sniper Shot'] = {'Liquefaction','Transfixion'},
    ['Slug Shot'] = {'Reverberation','Transfixion','Detonation'},
    ['Blast Shot'] = {'Induration','Transfixion'},
    ['Heavy Shot'] = {'Fusion'},
    ['Detonator'] = {'Fusion','Transfixion'},
    ['Coronach'] = {'Darkness','Fragmentation'},
    ['Trueflight'] = {'Fragmentation','Scission'},
    ['Leaden Salute'] = {'Gravitation','Transfixion'},
    ['Numbing Shot'] = {'Induration','Detonation','Impaction'},
    ['Wildfire'] = {'Darkness','Gravitation'},
    ['Last Stand'] = {'Fusion','Reverberation'},
    ['Terminus'] = {'Induration','Reverberation','Fusion'},
    ['Exenterator'] = {'Fragmentation','Scission'},
    ['Chant du Cygne'] = {'Light','Distortion'},
    ['Requiescat'] = {'Gravitation','Scission'},
    ['Knights of Rotund'] = {'Light'},
    ['Final Paradise'] = {'Light'},
    ['Fast Blade II'] = {'Fusion'},
    ['Dragon Blow'] = {'Distortion'},
    ['Maru Kala'] = {'Detonation','Compression','Distortion'},
    ['Ruthless Stroke'] = {'Liquefaction','Impaction','Fragmentation'},
    ['Imperator'] = {'Detonation','Compression','Distortion'},
    ['Dagda'] = {'Transfixion','Scission','Gravitation'},
    ['Oshala'] = {'Induration','Reverberation','Fusion'},
    ['Uriel Blade'] = {'Light','Fragmentation'},
    ['Glory Slash'] = {'Light','Fusion'},
}

return D
